### ISSUE TITLE
Review HW8

### ISSUE THREAD

**Issue by setwith** [DmytrioO/RubyHW#15]
Вцілому завдання виконане. Фільтрація відбувається коректно,  пагінація працює, серіалайзер додано 👍

Я б радив прорефакторити код. А саме:
- [x]  в routes.rb не варто робити вкладений роут _resources :findpost_ .  Адже в адресній стрічнці для пошуку будь-якого поста нам необхідно ввести post_id (/api/v1/posts/:post_id/findpost). Resources створює рути для всіх екшенів  CRUD, що в дамому випадку не потрібно,  адже використовуємо лише індекс.
Також, думаю буде лишнім для даної фічі робити окремий контролер. Якщо бажаєте зробити для пошуку окремий метод, то краще реалізувати цей метод в контролері Post та в routes.rb прописати щось на зразок
```ruby
resources :posts do
get :find_post
end
```

- [x] для серіалайзера в методі show варто використовувати _serializer:_ замість _each_serializer:_

- [x] для фільтрації я б радив використовувати scope в моделі post.  Це значно спростить код та зробить його більш читабельним

- [x] варто реалізувати пошук по імені автора, а не по  author_id.  Це можна реалізувати використовуючи 
 ```ruby
joins(:author).where('author.name ILIKE ?', "%#{name}%")
 ```

- [x] таким самим чином можна спростити логіку пошуку по тегах

**Comment by DmytrioO** [comment]
Дякую за фідбек! Прорефакторив код згідно з вашими порадами - стало краще!
