### ISSUE TITLE
Ruby HW2 task2 feedback

### ISSUE THREAD

**Issue by MaksHostroushko** [DmytrioO/RubyHW#4]
1. Please, use initialize for instance variables instead of @@variables
```
@@chmood = 1 
@@chhunger = 1
@@chtire = 1
@@game_true = 0
@@status_pet = 'живий'
  ```
  
  2. `@time = Time.new - 600`
  Please, don't use a magic number(like 600)
  You can use [CONSTANTs](https://www.rubyguides.com/2017/07/ruby-constants/) for fixed values
  
  3. You have a lot of duplicated code
  First of all, try to use `case` instead of `if/else` with the same conditions
  Like here https://github.com/DmytrioO/RubyHW/blob/main/HW2/Game/Game.rb#L469...L485
  3.1 Also, try to divide your methods into smaller methods. Because, for now, it looks is not very readable
  
  4. Please, review your code according to [this style guide ](https://github.com/rubocop/ruby-style-guide)

**Comment by DmytrioO** [comment]
Thank you for you feedback! I realized my mistakes, and I will be fix them as soon as possible.
