### ISSUE TITLE
feedback "Tamagotchi on Rack"

### ISSUE THREAD

**Issue by EugeneShitov** [DmytrioO/RubyHW#5]
### The game is cool.
Mentors, don't drink the `самогон`! 
_
Subjectively - it was difficult for me to read the font, at some points, simply because of the color of the background and text, I could not read the text. [I recommend getting acquainted.](https://products.aspose.app/html/ru/contrast-checker)
Мinimum contrast ratio of 5, anything below is bad.
_

1. In the main file, 750 strips of code, in my opinion, this is a lot. I would split it into multiple files.
2. Point one made it difficult to read and understand the code.
3. A lot of text, but it's already a nitpick, as far as I'm concerned.

Other - OK!
---

**Comment by DmytrioO** [comment]
Thank you for your feedback! I will try to fix mistakes as soon as possible.
